### ISSUE TITLE
无法完成编译

### ISSUE THREAD

**Issue by kenee** [ShopeX/bscope#1]
src目录下缺以下库
1. libnet
2. msgpack-0.5.4
3. rabbitmq-c-0.4.0

**Comment by flaboy** [comment]
依赖的库当然要提前安装好

Yum install libnet-devel msgpack-devel rabbitmq-devel

发件人： Ken
已发送： 2015年4月23日星期四 12:10
收件人： shopex/bscope
答复： shopex/bscope
主题： [bscope] 无法完成编译 (#1)

src目录下缺以下库
1. libnet
2. msgpack-0.5.4
3. rabbitmq-c-0.4.0

---

Reply to this email directly or view it on GitHub:
https://github.com/shopex/bscope/issues/1
